PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS STORIES (
  STORY_ID TEXT PRIMARY KEY,
  SOURCE_PATH TEXT NOT NULL UNIQUE,
  CONTENT_HASH TEXT NOT NULL,
  TITLE TEXT NOT NULL,
  SUMMARY_SHORT TEXT,
  SUMMARY_LONG TEXT,
  GENRE TEXT,
  TONE TEXT,
  SETTING TEXT,
  TAGS_JSON TEXT NOT NULL DEFAULT '[]',
  THEMES_JSON TEXT NOT NULL DEFAULT '[]',
  CONTENT_NOTES_JSON TEXT NOT NULL DEFAULT '[]',
  WORD_COUNT INTEGER NOT NULL DEFAULT 0,
  CHUNK_COUNT INTEGER NOT NULL DEFAULT 0,
  R2_KEY TEXT NOT NULL,
  CHUNKS_KEY TEXT,
  UPDATED_AT TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_STORIES_GENRE ON STORIES (GENRE);
CREATE INDEX IF NOT EXISTS IDX_STORIES_TONE ON STORIES (TONE);
CREATE INDEX IF NOT EXISTS IDX_STORIES_UPDATED_AT ON STORIES (UPDATED_AT);
CREATE INDEX IF NOT EXISTS IDX_STORIES_SOURCE_PATH ON STORIES (SOURCE_PATH);

CREATE TABLE IF NOT EXISTS TAGS (
  TAG TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS STORY_TAGS (
  STORY_ID TEXT NOT NULL,
  TAG TEXT NOT NULL,
  PRIMARY KEY (STORY_ID, TAG),
  FOREIGN KEY (STORY_ID) REFERENCES STORIES (STORY_ID) ON DELETE CASCADE,
  FOREIGN KEY (TAG) REFERENCES TAGS (TAG) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_STORY_TAGS_TAG ON STORY_TAGS (TAG);
