PRAGMA foreign_keys = ON;

ALTER TABLE STORIES ADD COLUMN RAW_HASH TEXT;
ALTER TABLE STORIES ADD COLUMN CANON_HASH TEXT;
ALTER TABLE STORIES ADD COLUMN STORY_STATUS TEXT NOT NULL DEFAULT 'OK';
ALTER TABLE STORIES ADD COLUMN SOURCE_COUNT INTEGER NOT NULL DEFAULT 1;
ALTER TABLE STORIES ADD COLUMN CANON_TEXT_SOURCE TEXT;
ALTER TABLE STORIES ADD COLUMN EXTRACT_METHOD TEXT;
ALTER TABLE STORIES ADD COLUMN STATUS_NOTES TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS IDX_STORIES_CANON_HASH ON STORIES (CANON_HASH);
CREATE INDEX IF NOT EXISTS IDX_STORIES_STATUS ON STORIES (STORY_STATUS);
CREATE INDEX IF NOT EXISTS IDX_STORIES_SOURCE_COUNT ON STORIES (SOURCE_COUNT);

CREATE TABLE IF NOT EXISTS STORY_SOURCES (
  STORY_ID TEXT NOT NULL,
  SOURCE_PATH TEXT NOT NULL,
  RAW_HASH TEXT NOT NULL,
  INGESTED_AT TEXT NOT NULL,
  SOURCE_TYPE TEXT NOT NULL,
  EXTRACT_METHOD TEXT,
  TITLE_FROM_SOURCE TEXT,
  PRIMARY KEY (STORY_ID, SOURCE_PATH),
  FOREIGN KEY (STORY_ID) REFERENCES STORIES (STORY_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_STORY_SOURCES_SOURCE_PATH ON STORY_SOURCES (SOURCE_PATH);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_STORY_SOURCES_SOURCE_PATH_UNIQUE ON STORY_SOURCES (SOURCE_PATH);
CREATE INDEX IF NOT EXISTS IDX_STORY_SOURCES_STORY_ID ON STORY_SOURCES (STORY_ID);
CREATE INDEX IF NOT EXISTS IDX_STORY_SOURCES_RAW_HASH ON STORY_SOURCES (RAW_HASH);
