PRAGMA foreign_keys = ON;

ALTER TABLE STORIES ADD COLUMN IS_READ INTEGER NOT NULL DEFAULT 0;
ALTER TABLE STORIES ADD COLUMN USER_TAGS_JSON TEXT NOT NULL DEFAULT '[]';

CREATE INDEX IF NOT EXISTS IDX_STORIES_IS_READ ON STORIES (IS_READ);

CREATE TABLE IF NOT EXISTS USER_TAGS (
  TAG TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS STORY_USER_TAGS (
  STORY_ID TEXT NOT NULL,
  TAG TEXT NOT NULL,
  PRIMARY KEY (STORY_ID, TAG),
  FOREIGN KEY (STORY_ID) REFERENCES STORIES (STORY_ID) ON DELETE CASCADE,
  FOREIGN KEY (TAG) REFERENCES USER_TAGS (TAG) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_STORY_USER_TAGS_TAG ON STORY_USER_TAGS (TAG);
CREATE INDEX IF NOT EXISTS IDX_STORY_USER_TAGS_STORY_ID ON STORY_USER_TAGS (STORY_ID);
