PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS STORY_TEXT (
  STORY_ID TEXT PRIMARY KEY,
  TEXT_CONTENT TEXT NOT NULL,
  UPDATED_AT TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  FOREIGN KEY (STORY_ID) REFERENCES STORIES (STORY_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_STORY_TEXT_UPDATED_AT ON STORY_TEXT (UPDATED_AT);

CREATE VIRTUAL TABLE IF NOT EXISTS STORY_TEXT_FTS USING fts5(
  STORY_ID UNINDEXED,
  TEXT_CONTENT,
  tokenize = "unicode61 remove_diacritics 2"
);

CREATE TRIGGER IF NOT EXISTS TRG_STORY_TEXT_AI
AFTER INSERT ON STORY_TEXT
BEGIN
  INSERT INTO STORY_TEXT_FTS(rowid, STORY_ID, TEXT_CONTENT)
  VALUES (new.rowid, new.STORY_ID, new.TEXT_CONTENT);
END;

CREATE TRIGGER IF NOT EXISTS TRG_STORY_TEXT_AD
AFTER DELETE ON STORY_TEXT
BEGIN
  INSERT INTO STORY_TEXT_FTS(STORY_TEXT_FTS, rowid, STORY_ID, TEXT_CONTENT)
  VALUES ('delete', old.rowid, old.STORY_ID, old.TEXT_CONTENT);
END;

CREATE TRIGGER IF NOT EXISTS TRG_STORY_TEXT_AU
AFTER UPDATE ON STORY_TEXT
BEGIN
  INSERT INTO STORY_TEXT_FTS(STORY_TEXT_FTS, rowid, STORY_ID, TEXT_CONTENT)
  VALUES ('delete', old.rowid, old.STORY_ID, old.TEXT_CONTENT);
  INSERT INTO STORY_TEXT_FTS(rowid, STORY_ID, TEXT_CONTENT)
  VALUES (new.rowid, new.STORY_ID, new.TEXT_CONTENT);
END;
