PRAGMA foreign_keys = ON;

DROP TRIGGER IF EXISTS TRG_STORY_TEXT_AI;
DROP TRIGGER IF EXISTS TRG_STORY_TEXT_AD;
DROP TRIGGER IF EXISTS TRG_STORY_TEXT_AU;

CREATE TRIGGER IF NOT EXISTS TRG_STORY_TEXT_AI
AFTER INSERT ON STORY_TEXT
BEGIN
  INSERT INTO STORY_TEXT_FTS(rowid, STORY_ID, TEXT_CONTENT)
  VALUES (new.rowid, new.STORY_ID, new.TEXT_CONTENT);
END;

CREATE TRIGGER IF NOT EXISTS TRG_STORY_TEXT_AD
AFTER DELETE ON STORY_TEXT
BEGIN
  DELETE FROM STORY_TEXT_FTS WHERE rowid = old.rowid;
END;

CREATE TRIGGER IF NOT EXISTS TRG_STORY_TEXT_AU
AFTER UPDATE ON STORY_TEXT
BEGIN
  DELETE FROM STORY_TEXT_FTS WHERE rowid = old.rowid;
  INSERT INTO STORY_TEXT_FTS(rowid, STORY_ID, TEXT_CONTENT)
  VALUES (new.rowid, new.STORY_ID, new.TEXT_CONTENT);
END;

INSERT INTO STORY_TEXT_FTS(STORY_TEXT_FTS) VALUES ('rebuild');
